// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Data;

#nullable disable

namespace UserManagement.Data.Migrations
{
    [DbContext(typeof(UserManagementDbContext))]
    [Migration("20250626193151_Seeding_User_Table")]
    partial class Seeding_User_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserManagement.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateOfBirth = new DateOnly(1993, 11, 12),
                            Email = "ploew@example.com",
                            Forename = "Peter",
                            IsActive = true,
                            Surname = "Loew"
                        },
                        new
                        {
                            Id = 2L,
                            DateOfBirth = new DateOnly(1985, 4, 17),
                            Email = "bfgates@example.com",
                            Forename = "Benjamin Franklin",
                            IsActive = true,
                            Surname = "Gates"
                        },
                        new
                        {
                            Id = 3L,
                            DateOfBirth = new DateOnly(1992, 8, 23),
                            Email = "ctroy@example.com",
                            Forename = "Castor",
                            IsActive = false,
                            Surname = "Troy"
                        },
                        new
                        {
                            Id = 4L,
                            DateOfBirth = new DateOnly(1976, 2, 5),
                            Email = "mraines@example.com",
                            Forename = "Memphis",
                            IsActive = true,
                            Surname = "Raines"
                        },
                        new
                        {
                            Id = 5L,
                            DateOfBirth = new DateOnly(2001, 11, 30),
                            Email = "sgodspeed@example.com",
                            Forename = "Stanley",
                            IsActive = true,
                            Surname = "Goodspeed"
                        },
                        new
                        {
                            Id = 6L,
                            DateOfBirth = new DateOnly(1968, 7, 12),
                            Email = "himcdunnough@example.com",
                            Forename = "H.I.",
                            IsActive = true,
                            Surname = "McDunnough"
                        },
                        new
                        {
                            Id = 7L,
                            DateOfBirth = new DateOnly(1998, 5, 19),
                            Email = "cpoe@example.com",
                            Forename = "Cameron",
                            IsActive = false,
                            Surname = "Poe"
                        },
                        new
                        {
                            Id = 8L,
                            DateOfBirth = new DateOnly(1954, 9, 3),
                            Email = "emalus@example.com",
                            Forename = "Edward",
                            IsActive = false,
                            Surname = "Malus"
                        },
                        new
                        {
                            Id = 9L,
                            DateOfBirth = new DateOnly(1989, 3, 27),
                            Email = "dmacready@example.com",
                            Forename = "Damon",
                            IsActive = false,
                            Surname = "Macready"
                        },
                        new
                        {
                            Id = 10L,
                            DateOfBirth = new DateOnly(1973, 6, 14),
                            Email = "jblaze@example.com",
                            Forename = "Johnny",
                            IsActive = true,
                            Surname = "Blaze"
                        },
                        new
                        {
                            Id = 11L,
                            DateOfBirth = new DateOnly(1982, 10, 8),
                            Email = "rfeld@example.com",
                            Forename = "Robin",
                            IsActive = true,
                            Surname = "Feld"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
